### PR TITLE
Patch pooling issue in item recycler

### PR DESCRIPTION
**Pull request by jcmoore**
- covers case when sizeresponsible is pooled and size changes rapidly

@anthonykoerber @shuwen

### CODE REVIEW

**Comment by shuwen** [comment]
lgtm

**Comment by anthonykoerber** [comment]
👍  thx @jcmoore

**Comment by jcmoore** [comment]
@anthonykoerber @shuwen this latest commit should make priming the `grid.index` obsolete for the considered data resetting scenario

**Comment by anthonykoerber** [comment]
tested resetter - worked as expected without rendering glitches 👍

**Pull request merged**
