### PR TITLE
Refactor grunt build scripts

### PR DESCRIPTION
**Pull request by derekolson**
Prevent build/doc scripts from stepping on each other
Build into a separate .tmp folder

### CODE REVIEW

**Comment by dlasky** [comment]
tentative +1, i'd like to run it on tue too, but the mods look good

**Comment by dlasky** [comment]
@jcmoore @anthonykoerber

**Comment by anthonykoerber** [comment]
+1 LGTM - everything built as expected.

**Comment by derekolson** [comment]
@dlasky @anthonykoerber can you guys give this a try again.. i think for now this will have to do

**Comment by anthonykoerber** [comment]
a'ight @derekolson +1 LGTM everything worked as I expected it to.

**Comment by dlasky** [comment]
yeah so with the caveat that i'd like to address the somewhat indeterminate state of the build folder, i think its fine for now. (maybe docs:dev at a later point, but its not high priority)

+1

**Pull request merged**
