### PR TITLE
Update grid docs with 'indicate' property

### PR DESCRIPTION
**Pull request by sassomedia**

### CODE REVIEW

**Comment by sassomedia** [comment]
@jcmoore please CR, thanks!

**Comment by jcmoore** [comment]
Content looks good, just let me check it being served locally.  One moment please

**Comment by jcmoore** [comment]
ok @sassomedia , just 1 minor nitpick.

Looking at the docs page (by running `npm run build docs` and `npm run build live:docs`), the reality that `''` is an empty string is not terribly clear:

Image of new docs

Consider changing `"''"` to something like `"' ' (empty string)"`

**Comment by sassomedia** [comment]
@jcmoore ok, makes sense, will update

**Comment by jcmoore** [comment]
Thanks man, maybe also throw some single quotes around the other options too @sassomedia  (sorry for the delayed thought here)

**Comment by sassomedia** [comment]
also, seeing that in the preview, would the "loading  measuring" need two spaces in between? That's what I got from the source file. However, seems like the preview reduces that to one space.

**Comment by jcmoore** [comment]
Ahh so the regex in the split regex (https://github.com/MediaMath/strand/blob/master/src/strand-grid/strand-grid.js#L290) divides the string up wherever there is one or more whitespace characters -- the number of spaces/tabs is irrelevant.

**Comment by jcmoore** [comment]
Good stuff +2

**Comment by sassomedia** [comment]
ah, too fast, lol. Saw that the default also needed single quotes. Oh well.

**Comment by jcmoore** [comment]
ah, I'll patch it in with my changes to `.trim()`, no big deal

**Comment by sassomedia** [comment]
sounds good, thanks!

**Pull request merged**
