### PR TITLE
multi-file gulp build

### PR DESCRIPTION
**Pull request by shuwen**
grunt to gulp port with tasks split across multiple modules @dlasky @jcmoore

### CODE REVIEW

**Comment by dlasky** [comment]
rebase! (i think its bower again)

**Comment by dlasky** [comment]
one last thing that i think we need as well as the debugging functionality that i added late in the game for the bower link setup... let me know if you want to tackle this otherwise i can tack it on.

**Comment by shuwen** [comment]
rebased :recycle:

**Comment by shuwen** [comment]
*gulp*

**Pull request merged**
