### PR TITLE
Suggestions for capitalization, et cetera

### PR DESCRIPTION
**Pull request by Apophenia**
Hey Strand team,

I went through the docs and tried to standardize the capitalization of certain terms. I mostly cross-compared with the Polymer, Angular, and jQuery docs to see how they styled things like 'Ajax,' but for terms with no clear winner, I just stuck with whatever seemed to be most used within the docs already. I also made a couple other suggestions regarding grammar.

Open to refactoring; let me know what you think!

### CODE REVIEW

**Comment by anthonykoerber** [comment]
Thanks @apophenia for proofreading our docs! I'm sure there are some things we missed. We'll review between sessions today.

**Comment by anthonykoerber** [comment]
LGTM +1

**Comment by dlasky** [comment]
The data related changes look fine.

**Comment by derekolson** [comment]
@Apophenia Thanks! Want to squash and rebase?

**Comment by Apophenia** [comment]
@derekolson is this better?

**Comment by derekolson** [comment]
@Apophenia could you pull the latest changes on master and then rebase your PR?

**Pull request merged**
