### PR TITLE
Resolves an edge case where if target is set before attached an event…

### PR DESCRIPTION
**Pull request by dlasky**
… listener could leak

@jcmoore @anthonykoerber 

cc @chartnett

### CODE REVIEW

**Comment by anthonykoerber** [comment]
@dlasky looks like you removed `_removeListener` but we've still got `_removeListener(oldTrigger)` in there

**Comment by dlasky** [comment]
probably dont need the if anymore either actually since its gated, but the target should be somethign else

**Comment by anthonykoerber** [comment]
LGTM 👍

**Comment by jcmoore** [comment]
+1

**Pull request merged**
